language: node_js

node_js:
  - node

before_deploy:
  - npm run build
  
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: docs/.vuepress/dist
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
